# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Data Science and Memes
description: This is a place where I write freely and try to meme up the complicated stuff and un-complicate it for myself and everyone else.
github_username: amaarora

# Email and twitter are optional:
email: yjanaky@gmail.com
twitter_username: yashwantreddy
linkedin_username: ash-jankay

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-158677010-1

# Everything below here can be ignored, unless you want to change the theme entirely
theme: jekyll-theme-minimal
plugins:
  # - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
